version: "3.9"

services:
  my-postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5

  api-container:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-container
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@my-postgres:5432/mydb
      STREAM_URL: http://stream-container:8001/stream
    ports:
      - "8000:8000"
    depends_on:
      my-postgres:
        condition: service_healthy
      stream-container:
        condition: service_started

  stream-container:
    build:
      context: .
      dockerfile: Dockerfile.stream
    container_name: stream-container
    ports:
      - "8001:8001"
    depends_on:
      my-postgres:
        condition: service_healthy