FROM python:3.11-slim

WORKDIR /app

COPY . .

# Install dependencies
RUN pip install --upgrade pip && \
    pip install fastapi uvicorn sqlalchemy psycopg2-binary requests

# Run stream server
CMD ["python", "-m", "uvicorn", "stream_server:app", "--host", "0.0.0.0", "--port", "8001"]