# docker-compose.yml
services:
  my-postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5

  api-container:
    build:
      context: .
      dockerfile: ./Dockerfile.api   # Dockerfile 위치 수정
    container_name: api-container
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@my-postgres:5432/mydb
    ports:
      - "8000:8000"
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - my-network

  stream-container:
    build:
      context: .
      dockerfile: ./Dockerfile.stream  # Dockerfile 위치 수정
    container_name: stream-container
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@my-postgres:5432/mydb
    depends_on:
      my-postgres:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge