FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY stream_server.py ./

ENV PYTHONPATH=/app

# Dockerfile.stream
CMD ["uvicorn", "stream_server:app", "--host", "0.0.0.0", "--port", "8001"]