# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

COPY . .
RUN pip install --upgrade pip && \
    pip install fastapi uvicorn sqlalchemy psycopg2-binary requests

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]